garb/urls.py
from django.urls import path
from django.views.i18n import JavaScriptCatalog

app_name = 'garb'

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='jsi18n'),
]

garb/forms.py
from copy import deepcopy
from dataclasses import fields

from django import forms
from django.forms.fields import DateField
from django.forms.utils import ErrorDict, flatatt
from django.utils.safestring import mark_safe


def with_metaclass(meta, *bases):
    return meta(str("NewBase"), bases, {})


class Fieldset(object):
    def __init__(self, form, name, boundfields, legend='', classes='', description=''):
        self.form = form
        self.boundfields = boundfields
        self.classes = classes
        self.description = mark_safe(description)
        self.name = name

    def _errors(self):
        return ErrorDict(((k, v) for (k, v) in self.form.errors.iteritems() if k in [f.name for f in self.boundfields]))
    errors = property(_errors)

    def __iter__(self):
        for bf in self.boundfields:
            if isinstance(bf.field, forms.fields.DateField):
                if 'class' in bf.field.widget.attrs:
                    bf.field.widget.attrs['class'] += ' vDateField'
                else:
                    bf.field.widget.attrs.update({'class':'vDateField'})
            yield _mark_row_attrs(bf, self.form)

    def __repr__(self):
        return "%s('%s', %s, classes='%s', description='%s')" % ( self.__class__.__name__, self.name, [f.name for f in self.boundfields], self.classes, self.description)


class FieldsetCollection(object):
    def __init__(self, form, fieldsets):
        self.form = form
        self.fieldsets = fieldsets
        self._cached_fieldsets = []

    def __len__(self):
        return len(self.fieldsets) or 1

    def __iter__(self):
        if not self._cached_fieldsets:
            self._gather_fieldsets()
        for field in self._cached_fieldsets:
            yield field

    def __getitem__(self, key):
        if not self._cached_fieldsets:
            self._gather_fieldsets()
        for field in self._cached_fieldsets:
            if field.name == key:
                return field
        raise KeyError

    def _gather_fieldsets(self):
        if not self.fieldsets:
            self.fieldsets = (('', {'fields': self.form.fields.keys(), 'legend': ''}),)
        for name, options in self.fieldsets:
            try:
                field_names = [n for n in options['fields'] if n in self.form.fields]
            except KeyError:
                message = "Fieldset definition must include 'fields' option."
                raise ValueError(message)
            boundfields = [forms.BoundField(self.form, self.form.fields[n], n) for n in field_names]
            self._cached_fieldsets.append(Fieldset(self.form, name, boundfields, options.get('legend', None), ' '.join(options.get('classes', (''))), options.get('description', '')))


def _get_meta_attr(attrs, attr, default):
    try:
        ret = getattr(attrs['Meta'], attr)
    except (KeyError, AttributeError):
        ret = default
    return ret


def _set_meta_attr(attrs, attr, value):
    try:
        setattr(attrs['Meta'], attr, value)
        return True
    except KeyError:
        return False


def get_fieldsets(bases, attrs):
    """Get the fieldsets definition from the inner Meta class."""
    fieldsets = _get_meta_attr(attrs, 'fieldsets', None)
    if fieldsets is None:
        #grab the fieldsets from the first base class that has them
        for base in bases:
            fieldsets = getattr(base, 'base_fieldsets', None)
            if fieldsets is not None:
                break
    fieldsets = fieldsets or []
    return fieldsets


def get_fields_from_fieldsets(fieldsets):
    """Get a list of all fields included in a fieldsets definition."""
    fields = []
    try:
        for name, options in fieldsets:
            fields.extend(options['fields'])
    except (TypeError, KeyError):
        raise ValueError('"fieldsets" must be an iterable of two-tuples, ' 'and the second tuple must be a dictionary ' 'with a "fields" key')
    return fields or None


def get_row_attrs(bases, attrs):
    """Get the row_attrs definition from the inner Meta class."""
    return _get_meta_attr(attrs, 'row_attrs', {})


def get_submit_text(bases, attrs):
    """Get the row_attrs definition from the inner Meta class."""
    return _get_meta_attr(attrs, 'submit_text', {})


def _mark_row_attrs(bf, form):
    row_attrs = deepcopy(form._row_attrs.get(bf.name, {}))
    if bf.field.required:
        req_class = 'required'
    else:
        req_class = 'optional'
    if bf.errors:
        req_class += ' error'
    if 'class' in row_attrs:
        row_attrs['class'] = row_attrs['class'] + ' ' + req_class
    else:
        row_attrs['class'] = req_class
    return bf


class GarbFormBaseMetaclass(type):
    def __new__(cls, name, bases, attrs):
        attrs['base_fieldsets'] = get_fieldsets(bases, attrs)
        fields = get_fields_from_fieldsets(attrs['base_fieldsets'])
        if (_get_meta_attr(attrs, 'fields', None) is None and
            _get_meta_attr(attrs, 'exclude', None) is None):
            _set_meta_attr(attrs, 'fields', fields)
        attrs['base_row_attrs'] = get_row_attrs(bases, attrs)
        attrs['submit_text'] = get_submit_text(bases, attrs)


        new_class = super(GarbFormBaseMetaclass, cls).__new__(cls, name, bases, attrs)
        return new_class


class GarbFormMetaclass(GarbFormBaseMetaclass, forms.forms.DeclarativeFieldsMetaclass):
    pass


class GarbModelFormMetaclass(GarbFormBaseMetaclass, forms.models.ModelFormMetaclass):
    pass


class GarbBaseForm(object):
    def __init__(self, *args, **kwargs):
        self._fieldsets = deepcopy(self.base_fieldsets)
        self._row_attrs = deepcopy(self.base_row_attrs)
        self._fieldset_collection = None
        super(GarbBaseForm, self).__init__(*args, **kwargs)

    @property
    def fieldsets(self):
        if not self._fieldset_collection:
            self._fieldset_collection = FieldsetCollection( self, self._fieldsets)
        return self._fieldset_collection

    def __iter__(self):
        for bf in super(GarbBaseForm, self).__iter__():
            yield _mark_row_attrs(bf, self)

    def __getitem__(self, name):
        bf = super(GarbBaseForm, self).__getitem__(name)
        return _mark_row_attrs(bf, self)


class GarbForm(with_metaclass(GarbFormMetaclass, GarbBaseForm), forms.Form):
    __doc__ = GarbBaseForm.__doc__


class GarbModelForm(with_metaclass(GarbModelFormMetaclass, GarbBaseForm), forms.ModelForm):
    __doc__ = GarbBaseForm.__doc__


class BasePreviewFormMixin(object):
    def __init__(self, *args, **kwargs):
        super(BasePreviewFormMixin, self).__init__(*args, **kwargs)
        self.preview = self.check_preview(kwargs.get('data', None))

    def check_preview(self, data):
        if data and data.get('submit', '').lower() == u'preview':
            return True
        return False

    def is_valid(self, *args, **kwargs):
        if self.preview:
            return False
        return super(BasePreviewFormMixin, self).is_valid()


class PreviewModelForm(BasePreviewFormMixin, GarbModelForm):
    pass


class PreviewForm(BasePreviewFormMixin, GarbForm):
    pass

garb/views.py
class ViewContextMixin:
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"title": self.title, **(self.extra_context or {})})
        return context

garb/templates/base.html
{% load i18n static garb_tags %}
<!DOCTYPE html>
<html lang="en" >
    <head>
        <meta charset="utf-8" />
        <link rel="icon" href="#" />
        <title>{% block title %}{{ title|default_if_none:None|garb_title }}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css?family=Sora:400,500,700|Roboto&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.8.0/css/solid.css">
        <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.8.0/css/fontawesome.css">
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap-reboot.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css' %}">
        {% block extrastyle %}{% endblock %}
        {% block extrahead %}{% endblock %}

    </head>
    <body class="{{ "THEME"|settings_value }}">
        {% block header %}
            <header>
                <div>
                    <div class="titulo">
                        <a href= {% if user.is_authenticated %} {% url 'admin:index' %} {% else %} "/" {% endif %}>
                            <div class='logo'>{{ None|garb_title }}</div>
                        </a>
                    </div>
                </div>
                {% block header_msg %} {% endblock %}
                {% block header_login %}
                    {% if not is_popup %}
                        {% block login %}
                            <div class="headerlogin dropdown show">
                                {% if user.is_authenticated %}
                                    <div class="loginmenu">
                                        <a class="button dropdown-toggle" href="/#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ user.username }}
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                            {% if "ROUTE_PROFILE"|settings_value %} 
                                                <a class="dropdown-item button" href="{% url "ROUTE_PROFILE"|settings_value %}"><i class="fas fa-user-circle"></i>
                                                    {% if "NAME_PROFILE"|settings_value %} 
                                                        {{ "NAME_PROFILE"|settings_value|title }}
                                                    {% else %}
                                                        {% trans 'Account' %}
                                                    {% endif %}
                                                </a>
                                            {% endif %}
                                            {% block password_change %}
                                                <a class="dropdown-item button" href="{% url 'admin:password_change' %}"><i class="fas fa-key"></i>{% trans 'Change password' %}</a>
                                            {% endblock %}
                                            <form id="logout-form" method="post" action="{% url 'admin:logout' %}">
                                                {% csrf_token %}
                                                <button type="submit" class="dropdown-item button pl-2" ><i class="fas fa-sign-out-alt"></i> {% translate 'Log out' %}</button>
                                            </form>
                                        </div>
                                    </div>
                                {% else %}
                                    <a class="button" href="{% block login_link %} {% url 'admin:login' %}{% endblock %}" >
                                        <i class="fas fa-sign-in-alt"></i>{% trans 'Log in' %}
                                    </a>
                                {% endif %}
                            </div>
                        {% endblock %}
                    {% endif %}
                {% endblock %}
            </header>
        {% endblock %}
        {% block wrapper %}
            <div class="wrapper">
                    {% if not is_popup %}
                        {% block sidebar %}
                            {% if not "MENU_ONLY_AUTH"|settings_value or user.is_authenticated %}
                                <aside>
                                    {% include 'garb/menu.html' %}
                                </aside>
                            {% endif %}
                        {% endblock %}
                    {% endif %}
                <main  {% if is_popup %} class="margin-is-popup" {% endif %}>
                    {% block breadcrumbs %}
                        {% include "admin/includes/breadcrumbs.html" with nivel=1 breadcrumbs_action=title|default_if_none:None %} 
                    {% endblock %}
                    <div class="content-extend" >
                        {% block content %}  {% endblock %}
                    </div>
                </main>
            </div>
        {% endblock %}
    </body>
    <script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}" ></script>
    <script src="{% static 'vendor/jquery-toast-plugin/jquery.toast.min.js' %}" ></script>
    <script src="{% static 'vendor/pace/pace.min.js' %}" ></script>
    <script src="{% static 'js/garb_input.js' %}"></script>
    <script type="text/javascript">
        {% block messages %}
            {% if messages %}
                    {% for message in messages %}
                        $.toast({
                            text: `{{ message }}`,
                            icon: `{% firstof message.tags 'info' %}`,
                            loader: true,
                            position: 'bottom-right',
                            showHideTransition: 'slide',
                            hideAfter: 9000, 
                            allowToastClose: true,
                            stack: 20,
                        });
                    {% endfor %}
            {% endif %}
        {% endblock %}
    </script>
    {% if not "MENU_ONLY_AUTH"|settings_value or user.is_authenticated %}
        <script type="text/javascript">
            $('#menu .collapsed').on('click', function () {
                $('#menu .collapse').collapse('hide');
            });
        </script>
    {% endif %}
    {% block extrajs %}{% endblock %}
</html>

garb/templates/base_email.html
{% load  garb_tags %}
<!doctype html>
<html lang="en">
    <head>
        <title>{{ title|default_if_none:None|garb_title }}</title>
        <style>
            * {
                box-sizing: border-box;
                margin: 0;
                outline: 0;
                padding: 0;
            }
            body {
                margin: 0;
                padding: 0;
                mso-line-height-rule: exactly;
                min-width: 100%;
            }
            .wrapper {
                display: table;
                table-layout: fixed;
                width: 100%;
                min-width: 820px;
                -webkit-text-size-adjust: 100%;
                -ms-text-size-adjust: 100%;
                font-size: 14px;
                font-weight: 400;
                line-height: 1.43;
                padding-top:40px;
            }

            body, .wrapper {
                background-color: #eee;
            }

            /* Basic */
            table {
                border-collapse: collapse;
                border-spacing: 0;
            }
            table.center {
                margin: 40px auto 0 auto;
                width: 720px;
            }
            table.footer {
                margin: 0 auto;
                width: 720px;
            }
            td {
                padding: 0;
                vertical-align: top;
            }
            p {
                text-indent:1em;
            }

            .spacer,
            .border {
                font-size: 1px;
                line-height: 1px;
            }
            .spacer {
                width: 100%;
                line-height: 16px
            }
            .border {
                border: none;
            }

            .padded {
                padding: 30px;
            }
            strong, .strong {
                font-weight: 700;
            }
            h1, h2, h3, p, ol, ul, li {
                margin-top: 0;
            }
            ol, ul, li {
                padding-left: 0;
            }

            a {
                text-indent:0;
                text-decoration: none;
                color: #616161;
            }
            .btn {
                background-color:#216BB8;
                border:1px solid #216BB8;
                color:#ffffff;
                display:inline-block;
                font-family:Roboto, Helvetica, sans-serif;
                font-size:14px;
                font-weight:400;
                line-height:36px;
                text-align:center;
                text-transform:uppercase;
                width: 250px;
                height: 40px;
                padding: 0px 8px;
                margin: 0;
                outline: 0;
                outline-offset: 0;
                -webkit-text-size-adjust:none;
                mso-hide:all;
                border-radius: 5px;
                text-decoration: none;
            }
            a.btn {
                color:#ffffff;

            }

            /* Top panel */
            .title {
                text-align: left;
            }

            .subject {
                text-align: right;
            }

            .title {
                width: 360px;
                padding: 20px 50px;
                color: #216BB8;
                font-family: Roboto, Helvetica, sans-serif;
                font-weight: 400;
                font-size: 18px;
                line-height: 18px;
            }

            /* Header */
            .logo {
                padding: 16px 0;
            }


            /* Main */
            .main {
                -webkit-box-shadow: 0 2px 0 rgba(90,97,105,.11),0 4px 8px rgba(90,97,105,.12),0 10px 10px rgba(90,97,105,.06),0 7px 10px rgba(90,97,105,.1);
                -moz-box-shadow: 0 2px 0 rgba(90,97,105,.11),0 4px 8px rgba(90,97,105,.12),0 10px 10px rgba(90,97,105,.06),0 7px 10px rgba(90,97,105,.1);
                box-shadow: 0 2px 0 rgba(90,97,105,.11),0 4px 8px rgba(90,97,105,.12),0 10px 10px rgba(90,97,105,.06),0 7px 10px rgba(90,97,105,.1);
                border-radius: 5px;
                background-color: #fff;
                border-left: 6px solid #216BB8;
                margin-top:40px;
            }
            .content {
                width: 100%;
                padding: 20px;
            }

            .column-bottom {
                font-size: 8px;
                line-height: 8px;
            }
            .content h1 {
                margin-top: 0;
                margin-bottom: 16px;
                color: #212121;
                font-family: Roboto, Helvetica, sans-serif;
                font-weight: 400;
                font-size: 20px;
                line-height: 28px;
            }
            .content p {
                margin-top: 0;
                margin-bottom: 16px;
                color: #212121;
                font-family: Roboto, Helvetica, sans-serif;
                font-weight: 400;
                font-size: 16px;
                line-height: 24px;
            }
            .content .caption {
                color: #616161;
                font-size: 12px;
                line-height: 20px;
            }

            /* Footer */
            .signature, .subscription {
                vertical-align: bottom;
                width: 360px;
                padding: 20px 50px;
                text-align: right;
            }
        </style>
    </head>
    <body>
        <div class="wrapper center">
            <table class="main center">
                <tbody>
                    <tr>
                        <td class="column">
                            <div class="column-top">&nbsp;</div>
                            <table class="content" >
                                <tbody>
                                    <tr>
                                        <td class="padded">
                                            {% block content %} {% endblock %}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <div class="column-bottom">&nbsp;</div>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="spacer">&nbsp;</div>
                <table class="footer ">
                    <tbody>
                        <tr>
                            <td class="border" colspan="2">&nbsp;</td>
                        </tr>
                        <tr>
                            <td class="title" width="360">{{ title|default_if_none:None|garb_title }}</td>
                            <td class="subscription" width="360"> 
                                {% include "base_email_rodape.html" %}
                            </td>
                        </tr>
                    </tbody>
                </table>
                
            <br>
        </div>
    </body>
</html>

garb/templates/base_email_rodape.html
{% block rodape-direita %} 
    <strong class="strong block" href="#" target="_blank">{{ site_name }}</strong><br>
    <strong class="strong block" href="#" target="_blank">{% now "SHORT_DATETIME_FORMAT" %}</strong>
{% endblock %} 

garb/templates/base_error.html
{% extends "base.html" %}
{% load i18n static garb_tags %}

{% block header %} {% endblock %}
{% block breadcrumbs  %} 
<div class="breadcrumbs">
<div class="breadcrumbs">
    <ul class="breadcrumb login">
        <li>
        <a href="/"> {{ None|garb_title }} </a>
        <span class="divider">/</span>
        </li>
        <li class="active">
            {% block title %}{% endblock %}
        </li>
    </ul>
</div>
{% endblock %}

{% block content %} 
<div class='page_error'>
    <div class='number_error' >
        {% block error %} 404{% endblock %}
    </div>
    <div class='mensage_error'>
        {% block message %}{% endblock %}
    </div>
<div>

{% endblock %}

{% block sidebar %}
    <div class="login_bar">
    </div>
{% endblock %}

garb/templates/base_login.html
{% extends "admin/base_site.html" %}
{% load i18n static garb_tags %}

{% block header %} {% endblock %}
{% block breadcrumbs  %} 
<div class="breadcrumbs">
    <ul class="breadcrumb login">
        <li>
        <a href="/"> {{ None|garb_title }} </a>
        <span class="divider">/</span>
        </li>
        <li class="active">
            {% block breadcrumbs_login %}{% endblock %}
        </li>
    </ul>
</div>
{% endblock %}

{% block content %} {% endblock %}

{% block sidebar %}
    <div class="login_bar">
    </div>
{% endblock %}

garb/templates/base_pure.html
{% extends "admin/base_site.html" %}

{% block header_login %}{% endblock %}
{% block sidebar %}{% endblock %}
{% block breadcrumbs %}{% endblock %}

garb/templates/garb/form/garb_form.html
{% load i18n garb_form garb_tags static %}
{% block fields %}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">
    <script type="text/javascript" src="{% url 'garb:jsi18n' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/calendar.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script src="{% static '/admin/js/core.js' %}" /></script>
    <script src="{% static '/admin/js/SelectBox.js' %}" /></script>
    <script src="{% static '/admin/js/SelectFilter2.js' %}" /></script>

    <div class="change-columns">
        <div class="main-column-center">
            <div class="main-column-item">
                {% if form.non_field_errors or form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                {% for fieldset in form.fieldsets %}
                    <fieldset class="module aligned {{ fieldset.classes }}">
                        {% if fieldset.name  or fieldset.description %}
                            <div class="module-header">
                                {% if fieldset.name %}
                                    <div class="legend">{{ fieldset.name }}</div>
                                {% endif %}
                                {% if fieldset.description %}
                                    <div class="description">{{ fieldset.description|safe }}</div>
                                {% endif %}
                            </div>
                        {% endif %}
                        {% with fieldset as fields %}
                            {% for field in fields %}
                                {% if field.is_hidden %}
                                    {{ field }}
                                {% else %}
                                    <div class="form-row {% if field.name %} field-{{ field.name }}{% endif %} {% if field.errors %} is-invalid  {% endif %}">
                                        <div class="form-row-box fieldBox {% if field.name %} field-{{ field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors {% endif %}">
                                            {% if field|is_checkbox or field|is_radio%}
                                                <div class="form-row-label"></div>
                                                <div class="form-row-checkbox form-row-field ">
                                                    {{ field }}{{ field|label }}<div class="form-row-error"></div>
                                                </div>
                                            {% else %}
                                                <div class="form-row-label">
                                                    {{ field.label_tag }}
                                                    {% if field.field.widget|to_class_name == "FilteredSelectMultiple" or field.field.widget|to_class_name == "FilteredSelectMultiple" %}
                                            <div class="form-row-error">
                                                {% if field.errors %}{{ field.errors }}{% endif %}
                                            </div>
                                        {% endif %}
                                                </div>
                                                <div class="form-row-field ">
                                                    {% if field.is_readonly %}
                                                        {% if not "img" in field.contents %}
                                                            <div class="readonly">{{ field.contents }}</div>
                                                        {% endif %}
                                                    {% else %}
                                                        {{ field }}
                                                    {% endif %}
                                                    {% if not field.field.widget|to_class_name == "FilteredSelectMultiple" and not field.field.widget|to_class_name == "FilteredSelectMultiple" %}
                                                        <div class="form-row-error">
                                                            {% if field.errors %}{{ field.errors }}{% endif %}
                                                        </div>
                                                    {% endif %}
                                                </div>
                                            {% endif %}
                                        </div>
                                        {% if field.field.help_text %}
                                            <div class="help">{{ field.field.help_text|safe }}</div>
                                        {% endif %}

                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                    </fieldset>
                {% endfor %}
                {% if  form.submit_text %}
                    <fieldset class="module aligned {{ fieldset.classes }} text-right pr-5">
                        <button type="submit" class="btn button" name="_save">{{ form.submit_text }}</button>
                    </fieldset>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock fields %}

garb/templates/garb/form/label.html
<label for="{{ id }}" title="{{ label_text }}">{{ label_text|safe }}</label>

garb/templates/garb/menu.html
{% load garb_menu %}
<nav class="menu" id="menu">
    <div class="menu_detalhe"> </div>
    <ul>
        {% get_menu request as app_list %}
        {% for app in app_list %}
            <li {% if app.get_active %} class="active" {% endif %}>
                {% if app.childrens %}
                    <a class="collapsed" data-toggle="collapse" data-parent="#menu" href="#{{ app.get_chave }}" aria-expanded="{{app.collapsed|lower}}"  aria-controls="{{ app.get_chave }}">
                        <i class="fa {{ app.icon }} "></i><span>{{ app.label }}</span>
                    </a>
                    <ul class="collapse {{ app.collapsed|yesno:'show,' }}" id="{{ app.get_chave }}">
                        {% for app_sub in app.childrens %}
                            <li {% if app_sub.get_active %} class="active" {% endif %}>
                                <a href="{{ app_sub.get_url }}" {{ app_sub.get_target }}> </i>  <span>{{ app_sub.label }}</span> </a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <a href="{{ app.get_url }}" {{ app.get_target }}> <i class="fa {{ app.icon }} fa-lg "></i>  <span>{{ app.label }}</span> </a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</nav>